// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeDealsRealestat.Repository.Data;

#nullable disable

namespace Shiping.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240929194219_ordertype")]
    partial class ordertype
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Shiping.Repository.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Fees")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("SideFees")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7304),
                            Fees = 0f,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7350),
                            Name = "Cairo",
                            NameAr = "cairo"
                        });
                });

            modelBuilder.Entity("Shiping.Repository.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalBalance")
                        .HasColumnType("real");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Shiping.Repository.Models.ClientOrderPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientOrderPayments");
                });

            modelBuilder.Entity("Shiping.Repository.Models.ClientPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientPayment");
                });

            modelBuilder.Entity("Shiping.Repository.Models.CompanyInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AboutUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutUsAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneMumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutUs = "About  Ussss",
                            AboutUsAR = "3n 2lsherka",
                            PhoneMumber = "0112012811"
                        });
                });

            modelBuilder.Entity("Shiping.Repository.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Fees")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("District");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultFees")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7674),
                            EmployeeTypeId = 1,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7676),
                            Password = "P@ssw0rd",
                            PhoneNumber = "1234567890",
                            UserName = "Admin",
                            title = "MR"
                        });
                });

            modelBuilder.Entity("Shiping.Repository.Models.EmployeePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("permissrionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("permissrionId");

                    b.ToTable("EmployeePermission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7693),
                            EmployeeId = 1,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7695),
                            permissrionId = 1
                        });
                });

            modelBuilder.Entity("Shiping.Repository.Models.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllowDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermissrionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissrionId");

                    b.ToTable("EmployeeType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7501),
                            IsAllowDelete = false,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7503),
                            Name = "Admin",
                            NameAr = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7506),
                            IsAllowDelete = false,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7508),
                            Name = "Driver",
                            NameAr = "سواق"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7510),
                            IsAllowDelete = false,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7512),
                            Name = "Support",
                            NameAr = "دعم"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7514),
                            IsAllowDelete = false,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7515),
                            Name = "CallCenter",
                            NameAr = "خدمة عملاء"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7518),
                            IsAllowDelete = false,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7520),
                            Name = "Accountant",
                            NameAr = "محاسب"
                        });
                });

            modelBuilder.Entity("Shiping.Repository.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<float>("DriveryFees")
                        .HasColumnType("real");

                    b.Property<int?>("DriveryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float?>("MaterialFees")
                        .HasColumnType("real");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("OrderFees")
                        .HasColumnType("real");

                    b.Property<int?>("OrderTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("DriveryId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shiping.Repository.Models.OrderHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatusId");

                    b.ToTable("OrderHistories");
                });

            modelBuilder.Entity("Shiping.Repository.Models.OrderMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderMaterial");
                });

            modelBuilder.Entity("Shiping.Repository.Models.OrderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderType");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Permissrion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("Permissrion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7542),
                            EmployeeTypeId = 1,
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7543),
                            Name = "Admin",
                            NameAr = "Admin"
                        });
                });

            modelBuilder.Entity("Shiping.Repository.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7562),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7564),
                            Name = "new",
                            NameAr = "جديد"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7567),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7568),
                            Name = "preparing",
                            NameAr = "قيد التحضير"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7570),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7572),
                            Name = "picked up",
                            NameAr = "تم الاستلام"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7574),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7576),
                            Name = "shipped",
                            NameAr = "تم الشحن"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7578),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7580),
                            Name = "delivered",
                            NameAr = "تم التوصيل"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7582),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7583),
                            Name = "failed",
                            NameAr = "فشل"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7585),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7587),
                            Name = "failed fees collected",
                            NameAr = "فشل - تم جمع الرسوم"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7589),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7591),
                            Name = "could not reach client",
                            NameAr = "تعذر الوصول إلى العميل"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7593),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7595),
                            Name = "client reschedule",
                            NameAr = "العميل أعاد الجدولة"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7597),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7599),
                            Name = "cancelled",
                            NameAr = "ملغى"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7601),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7602),
                            Name = "returned to shipper",
                            NameAr = "تمت إعادة الشحنة إلى المرسل"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7604),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7606),
                            Name = "not received",
                            NameAr = "لم يتم الاستلام"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7608),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7610),
                            Name = "COD received",
                            NameAr = "تم استلام الدفع عند الاستلام"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7612),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7614),
                            Name = "missing info",
                            NameAr = "معلومات مفقودة"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7616),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7617),
                            Name = "on hold",
                            NameAr = "في الانتظار"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7619),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7621),
                            Name = "customer cancelled",
                            NameAr = "ألغى العميل"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7623),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7625),
                            Name = "not ready",
                            NameAr = "غير جاهز"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7627),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7628),
                            Name = "received at warehouse",
                            NameAr = "تم الاستلام في المستودع"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7630),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7632),
                            Name = "resend",
                            NameAr = "إعادة إرسال"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7634),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7636),
                            Name = "ready",
                            NameAr = "جاهز"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7638),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7640),
                            Name = "duplicated",
                            NameAr = "مكرر"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7642),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7643),
                            Name = "missing piece",
                            NameAr = "قطعة مفقودة"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7645),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 9, 29, 22, 42, 18, 199, DateTimeKind.Local).AddTicks(7647),
                            Name = "Paid",
                            NameAr = "تم الدفع"
                        });
                });

            modelBuilder.Entity("Shiping.Repository.Models.Client", b =>
                {
                    b.HasOne("Shiping.Repository.Models.City", "City")
                        .WithMany("Clients")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiping.Repository.Models.District", "District")
                        .WithMany("Clients")
                        .HasForeignKey("DistrictId");

                    b.Navigation("City");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Shiping.Repository.Models.ClientOrderPayment", b =>
                {
                    b.HasOne("Shiping.Repository.Models.Client", "Client")
                        .WithMany("ClientOrderPayments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Shiping.Repository.Models.ClientPayment", b =>
                {
                    b.HasOne("Shiping.Repository.Models.Client", "Client")
                        .WithMany("ClientPayment")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Shiping.Repository.Models.District", b =>
                {
                    b.HasOne("Shiping.Repository.Models.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Employee", b =>
                {
                    b.HasOne("Shiping.Repository.Models.City", "City")
                        .WithMany("Employees")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiping.Repository.Models.District", "District")
                        .WithMany("Employees")
                        .HasForeignKey("DistrictId");

                    b.HasOne("Shiping.Repository.Models.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("District");

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("Shiping.Repository.Models.EmployeePermission", b =>
                {
                    b.HasOne("Shiping.Repository.Models.Employee", "Employee")
                        .WithMany("EmployeePermissions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiping.Repository.Models.Permissrion", "permissrion")
                        .WithMany("employeePermissions")
                        .HasForeignKey("permissrionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("permissrion");
                });

            modelBuilder.Entity("Shiping.Repository.Models.EmployeeType", b =>
                {
                    b.HasOne("Shiping.Repository.Models.Permissrion", null)
                        .WithMany("EmployeeTypes")
                        .HasForeignKey("PermissrionId");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Order", b =>
                {
                    b.HasOne("Shiping.Repository.Models.City", "City")
                        .WithMany("Orders")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiping.Repository.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiping.Repository.Models.District", "District")
                        .WithMany("Orders")
                        .HasForeignKey("DistrictId");

                    b.HasOne("Shiping.Repository.Models.Employee", "Drivery")
                        .WithMany("Orders")
                        .HasForeignKey("DriveryId");

                    b.HasOne("Shiping.Repository.Models.Material", null)
                        .WithMany("Orders")
                        .HasForeignKey("MaterialId");

                    b.HasOne("Shiping.Repository.Models.OrderType", "OrderType")
                        .WithMany("Orders")
                        .HasForeignKey("OrderTypeId");

                    b.HasOne("Shiping.Repository.Models.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Client");

                    b.Navigation("District");

                    b.Navigation("Drivery");

                    b.Navigation("OrderType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Shiping.Repository.Models.OrderHistory", b =>
                {
                    b.HasOne("Shiping.Repository.Models.Employee", "Employee")
                        .WithMany("OrderHistories")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Shiping.Repository.Models.Order", "Order")
                        .WithMany("OrderHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiping.Repository.Models.Status", "Status")
                        .WithMany("OrderHistories")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Order");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Shiping.Repository.Models.OrderMaterial", b =>
                {
                    b.HasOne("Shiping.Repository.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiping.Repository.Models.Order", "Order")
                        .WithMany("OrderMaterials")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Permissrion", b =>
                {
                    b.HasOne("Shiping.Repository.Models.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("Shiping.Repository.Models.City", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Districts");

                    b.Navigation("Employees");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Client", b =>
                {
                    b.Navigation("ClientOrderPayments");

                    b.Navigation("ClientPayment");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shiping.Repository.Models.District", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Employees");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Employee", b =>
                {
                    b.Navigation("EmployeePermissions");

                    b.Navigation("OrderHistories");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shiping.Repository.Models.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Material", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Order", b =>
                {
                    b.Navigation("OrderHistories");

                    b.Navigation("OrderMaterials");
                });

            modelBuilder.Entity("Shiping.Repository.Models.OrderType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Permissrion", b =>
                {
                    b.Navigation("EmployeeTypes");

                    b.Navigation("employeePermissions");
                });

            modelBuilder.Entity("Shiping.Repository.Models.Status", b =>
                {
                    b.Navigation("OrderHistories");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
